package gofood;

import com.mysql.jdbc.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import javax.swing.table.TableModel;
import koneksi.conek;

public class AdminFrame extends javax.swing.JFrame {

    Model objek = new Model();
    private String id_resto = objek.getUser();
    private void showtable(){
        DefaultTableModel tbl = new DefaultTableModel(){
                                public Class getColumnClass(int c) {
                                  switch (c) {
                                    case 0: return Boolean.class;
                                    default: return String.class;
                                  }   
                                } };
        tbl.addColumn("Pilih");
        tbl.addColumn("id_menu");
        tbl.addColumn("Publikasi");
        tbl.addColumn("Menu");
        tbl.addColumn("Sumber Gambar");
        tbl.addColumn("Harga");
        tbl.addColumn("Diskon");
        tbl.addColumn("Deskripsi");
        setting.setModel(tbl);
        setting.getColumnModel().getColumn(0).setMaxWidth(40);
        setting.getColumnModel().getColumn(2).setMaxWidth(70);
        setting.getColumnModel().getColumn(3).setPreferredWidth(80);
        setting.getColumnModel().getColumn(4).setMaxWidth(200);
        setting.getColumnModel().getColumn(4).setMinWidth(150);
        setting.getColumnModel().getColumn(5).setMaxWidth(70);
        setting.getColumnModel().getColumn(6).setMaxWidth(70);
        setting.getColumnModel().getColumn(7).setPreferredWidth(200);
        TableColumnModel tcm = setting.getColumnModel();
        tcm.removeColumn(tcm.getColumn(1));
        setting.setShowHorizontalLines(true);
        String publish;
        int lenght = id_resto.length()+17;
        try{
            Statement st = (Statement) conek.GetConnection().createStatement();
            ResultSet rs = st.executeQuery("SELECT * FROM menu WHERE id_restoran='"+id_resto+"'");
            while(rs.next()){
                if (rs.getBoolean("publish")){
                    publish = "YA";
                }else{
                    publish = "TIDAK";
                }
                tbl.addRow(new Object []{
                    false,
                    rs.getString("id_menu"),
                    publish,
                    rs.getString("menu"),
                    rs.getString("gambar_menu").substring(lenght),
                    objek.formatUang(rs.getString("harga_menu")),
                    objek.formatUang(rs.getString("diskon_menu")),
                    rs.getString("deskripsi_menu")
                });
                setting.setModel(tbl);
            }
            rs.close();
        }catch(SQLException e){
            e.getStackTrace();
            JOptionPane.showMessageDialog(null, "Pencarian gagal");
        }
        setting.setDefaultEditor(Object.class, null);
    }
    public AdminFrame() {
        initComponents();
        showtable();
        koki.setIcon(objek.setUkuran(koki, "img\\admin.png"));
        Name.setText(objek.getString("restoran", "id_restoran ='"+id_resto+"'", "restoran"));
        menu_ireport.setIcon(objek.setUkuran(menu_ireport, "img\\show-ireport.png"));
        setting1.setIcon(objek.setUkuran(setting1, "img\\setting.png"));
        if(objek.getString("data_pesanan", "status='Diantar' AND id_restoran='"+objek.getUser()+"'", "id_menu")==null){
           inbox.setIcon(objek.setUkuran(inbox, "img\\read.png")); 
        }else{
            inbox.setIcon(objek.setUkuran(inbox, "img\\unread.png"));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        koki = new javax.swing.JLabel();
        Name = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        setting = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        menu_ireport = new javax.swing.JLabel();
        setting1 = new javax.swing.JLabel();
        inbox = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        pil_semua = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Admin GoFood");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        Name.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        Name.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Name.setText("Default_koki");
        Name.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        setting.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        setting.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setting.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                settingMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(setting);

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel2.setText("Daftar Setting Menu");

        jButton1.setText("Tambah Menu Baru");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("*Double klik Pada Tabel Untuk Edit Menu");

        jButton3.setText("Hapus Menu Tepilih");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        menu_ireport.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menu_ireport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_ireportMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menu_ireportMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                menu_ireportMouseReleased(evt);
            }
        });

        setting1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setting1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                setting1MouseClicked(evt);
            }
        });

        inbox.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        inbox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inboxMouseClicked(evt);
            }
        });

        jButton2.setText("Publikasikan Menu Terpilih");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton4.setText(" Menu Terpilih Tidak dipublikasikan");
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        pil_semua.setBackground(new java.awt.Color(255, 255, 255));
        pil_semua.setText("Pilih Semua");
        pil_semua.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pil_semua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pil_semuaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(420, 420, 420)
                                        .addComponent(jLabel2))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(pil_semua)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton4)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(menu_ireport, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(koki, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inbox, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(setting1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(koki, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(setting1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inbox, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(Name)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton3)
                            .addComponent(jLabel3)
                            .addComponent(jButton1)
                            .addComponent(jButton2)
                            .addComponent(jButton4)
                            .addComponent(pil_semua)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(menu_ireport, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        objek.setEditmenu(false);
        new settingMenu().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        TableModel model = setting.getModel();
        ArrayList<String> row = new ArrayList<>();
        int n = 0;
        for (int i = 0; i < model.getRowCount(); i++) {
            if(Boolean.valueOf(model.getValueAt(i, 0).toString())){
                row.add(model.getValueAt(i, 1).toString());
                n++;
            }
        }
        String img;
        for (int i=0; i< row.size(); i++) {
            img = objek.getString("menu", "id_menu='"+row.get(i)+"'", "gambar_menu").substring(5);
            objek.deldata(img);
            objek.delRow("menu","id_menu='"+row.get(i)+"'", null, null);
        }
        pil_semua.setSelected(false);
        showtable();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void settingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingMouseClicked
        if(evt.getClickCount()==2){
            int index = setting.getSelectedRow();
            TableModel model = setting.getModel();
            String menu = model.getValueAt(index, 1).toString();
            objek.setEditmenu(true);
            objek.setMenu(menu);
            new settingMenu().setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_settingMouseClicked

    private void menu_ireportMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_ireportMousePressed
        menu_ireport.setIcon(objek.setUkuran(menu_ireport, "img\\show-ireport-clicked.png"));
    }//GEN-LAST:event_menu_ireportMousePressed

    private void menu_ireportMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_ireportMouseReleased
        menu_ireport.setIcon(objek.setUkuran(menu_ireport, "img\\show-ireport.png"));
    }//GEN-LAST:event_menu_ireportMouseReleased

    private void menu_ireportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_ireportMouseClicked
        String command = "SELECT * FROM menu WHERE id_restoran='"+id_resto+"'";
        String laporan = "menu.jrxml";
        objek.getLaporan(command, laporan);
    }//GEN-LAST:event_menu_ireportMouseClicked

    private void setting1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_setting1MouseClicked
        new settingAdmin().setVisible(true);
        dispose();
    }//GEN-LAST:event_setting1MouseClicked

    private void inboxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inboxMouseClicked
        new Order_menu().setVisible(true);
        dispose();
    }//GEN-LAST:event_inboxMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        TableModel model = setting.getModel();
        ArrayList<String> row = new ArrayList<>();
        for (int i = 0; i < model.getRowCount(); i++) {
            if(Boolean.valueOf(model.getValueAt(i, 0).toString())){
                row.add(model.getValueAt(i, 1).toString());
            }
        }
        row.forEach((id) -> {
            objek.editRow("menu", "publish=1", "id_menu='"+id+"'", null, null);
        });
        pil_semua.setSelected(false);
        showtable();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        TableModel model = setting.getModel();
        ArrayList<String> row = new ArrayList<>();
        for (int i = 0; i < model.getRowCount(); i++) {
            if(Boolean.valueOf(model.getValueAt(i, 0).toString())){
                row.add(model.getValueAt(i, 1).toString());
            }
        }
        for (int i=0; i< row.size(); i++) {
            objek.delRow("data_pesanan", "id_menu="+row.get(i)+" AND status='Dipesan'", null, "Gagal menghapus pesanan");
            objek.editRow("menu", "publish=0", "id_menu='"+row.get(i)+"'", null, null);
        }
        pil_semua.setSelected(false);
        showtable();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void pil_semuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pil_semuaActionPerformed
        TableModel model = setting.getModel();
        if(pil_semua.isSelected()){
            for (int i = 0; i < model.getRowCount(); i++) {
                model.setValueAt(true, i, 0);
            }
        }else{
            for (int i = 0; i < model.getRowCount(); i++) {
                model.setValueAt(false, i, 0);
            }
        }
    }//GEN-LAST:event_pil_semuaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Name;
    private javax.swing.JLabel inbox;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel koki;
    private javax.swing.JLabel menu_ireport;
    private javax.swing.JCheckBox pil_semua;
    private javax.swing.JTable setting;
    private javax.swing.JLabel setting1;
    // End of variables declaration//GEN-END:variables
}
