/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gofood;

import com.mysql.jdbc.Statement;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import javax.swing.table.TableModel;
import koneksi.conek;

/**
 *
 * @author Naufal
 */
public class Inbox extends javax.swing.JFrame {
    
    Model objek = new Model();
    private String user = objek.getUser();
    private int row1, row2;
    private int showTabel(JTable Tabel, String status){
        DefaultTableModel tbl = new DefaultTableModel(){
                                public Class getColumnClass(int c) {
                                  switch (c) {
                                    case 0: return Boolean.class;
                                    default: return String.class;
                                  }   
                                } };
            tbl.addColumn("pilih");
            tbl.addColumn("id");
            tbl.addColumn("Dari");
            tbl.addColumn("Pesan");
            Tabel.setModel(tbl);
        try{
            Statement statement = (Statement) conek.GetConnection().createStatement();
            ResultSet res = statement.executeQuery("SELECT * FROM pesan WHERE id_user='"+user+"' AND baca="+status);
            while (res.next()){
                tbl.addRow(new Object []{
                    false,
                    res.getString("id"),
                    res.getString("dari"),
                    res.getString("pesan")
                });
                Tabel.setModel(tbl);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Tabel Error!!!");
        }
        Tabel.getColumnModel().getColumn(0).setMaxWidth(40);
        Tabel.getColumnModel().getColumn(2).setMaxWidth(80);
        TableColumnModel tcm = Tabel.getColumnModel();
        tcm.removeColumn(tcm.getColumn(1));
        Tabel.setShowHorizontalLines(true);
        Tabel.setDefaultEditor(Object.class, null);
        return tbl.getRowCount();
    }

    public Inbox() {
        initComponents();
        row1 = showTabel(tbl_unread,"1");
        row2 = showTabel(tbl_readed,"0");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_unread = new javax.swing.JTable();
        pil_semua = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_readed = new javax.swing.JTable();
        pil_semuaR = new javax.swing.JCheckBox();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jTabbedPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTabbedPane1.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        tbl_unread.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_unread.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tbl_unread.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_unreadMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_unread);

        pil_semua.setBackground(new java.awt.Color(255, 255, 255));
        pil_semua.setText("Pilih Semua");
        pil_semua.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pil_semua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pil_semuaActionPerformed(evt);
            }
        });

        jButton1.setText("Tandai terpilih telah di baca");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("*Double klik untuk baca pesan");

        jButton2.setText("Hapus Pesan terpilih");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(pil_semua)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pil_semua)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Belum Dibaca", jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        tbl_readed.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_readed.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tbl_readed.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_readedMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbl_readed);

        pil_semuaR.setBackground(new java.awt.Color(255, 255, 255));
        pil_semuaR.setText("Pilih semua");
        pil_semuaR.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pil_semuaR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pil_semuaRActionPerformed(evt);
            }
        });

        jButton3.setText("Hapus Pesan terpilih");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel2.setText("*Double klik untuk baca pesan");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(pil_semuaR)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(pil_semuaR)
                        .addComponent(jButton3))
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Telah Dibaca ", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void pil_semuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pil_semuaActionPerformed
        TableModel model = tbl_unread.getModel();
        if(pil_semua.isSelected()){
            for (int i = 0; i < model.getRowCount(); i++) {
                model.setValueAt(true, i, 0);
            }
        }else{
            for (int i = 0; i < model.getRowCount(); i++) {
                model.setValueAt(false, i, 0);
            }
        }
    }//GEN-LAST:event_pil_semuaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        TableModel model = tbl_unread.getModel();
        ArrayList<String> row = new ArrayList<>();
        for (int i = 0; i < row1; i++) {
            if(Boolean.valueOf(model.getValueAt(i, 0).toString())){
                row.add(model.getValueAt(i, 1).toString());
            }
        }
        row.forEach((id) -> {
            objek.editRow("pesan", "baca=0", "id='"+id+"'", null, null);
        });
        row1 = showTabel(tbl_unread,"1");
        row2 = showTabel(tbl_readed,"0");
        pil_semua.setSelected(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tbl_unreadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_unreadMouseClicked
        if(evt.getClickCount() == 2){
            int index = tbl_unread.getSelectedRow();
            TableModel model = tbl_unread.getModel();
            String id = model.getValueAt(index, 1).toString();
            String from = model.getValueAt(index, 2).toString();
            String pesan = model.getValueAt(index, 3).toString();
            String Message = "Dari : "+from+"\n\n"+pesan+"";
            JOptionPane.showMessageDialog(null, Message, "Info Pesanan", JOptionPane.PLAIN_MESSAGE);
            objek.editRow("pesan", "baca=0", "id='"+id+"'", null, null);
            row1 = showTabel(tbl_unread,"1");
            row2 = showTabel(tbl_readed,"0");
        }
    }//GEN-LAST:event_tbl_unreadMouseClicked

    private void tbl_readedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_readedMouseClicked
        if(evt.getClickCount() == 2){
            int index = tbl_readed.getSelectedRow();
            TableModel model = tbl_readed.getModel();
            String from = model.getValueAt(index, 0).toString();
            String pesan = model.getValueAt(index, 1).toString();
            String Message = "Dari : "+from+"\n\n"+pesan+"";
            JOptionPane.showMessageDialog(null, Message, "Info Pesanan", JOptionPane.PLAIN_MESSAGE);
        }
    }//GEN-LAST:event_tbl_readedMouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        new User().setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    private void pil_semuaRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pil_semuaRActionPerformed
        TableModel model = tbl_readed.getModel();
        if(pil_semuaR.isSelected()){
            for (int i = 0; i < model.getRowCount(); i++) {
                model.setValueAt(true, i, 0);
            }
        }else{
            for (int i = 0; i < model.getRowCount(); i++) {
                model.setValueAt(false, i, 0);
            }
        }
    }//GEN-LAST:event_pil_semuaRActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        TableModel model = tbl_unread.getModel();
        ArrayList<Integer> row = new ArrayList<>();
        int n = 0;
        for (int i = 0; i < row1; i++) {
            if(Boolean.valueOf(model.getValueAt(i, 0).toString())){
                row.add(Integer.parseInt(model.getValueAt(i, 1).toString()));
                n++;
            }
        }
        row.forEach((id) -> {
            objek.delRow("pesan","id="+id, null, null);
        });
        row1 = showTabel(tbl_unread,"1");
        row2 = showTabel(tbl_readed,"0");
        pil_semua.setSelected(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        TableModel model = tbl_readed.getModel();
        ArrayList<Integer> row = new ArrayList<>();
        int n = 0;
        for (int i = 0; i < row2; i++) {
            if(Boolean.valueOf(model.getValueAt(i, 0).toString())){
                row.add(Integer.parseInt(model.getValueAt(i, 1).toString()));
                n++;
            }
        }
        row.forEach((id) -> {
            objek.delRow("pesan","id="+id, null, null);
        });
        row1 = showTabel(tbl_unread,"1");
        row2 = showTabel(tbl_readed,"0");
        pil_semuaR.setSelected(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inbox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inbox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inbox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inbox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inbox().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JCheckBox pil_semua;
    private javax.swing.JCheckBox pil_semuaR;
    private javax.swing.JTable tbl_readed;
    private javax.swing.JTable tbl_unread;
    // End of variables declaration//GEN-END:variables
}
